version: '3.1'

services:
  server:
    build: .
    environment:
      USERS_MONGO_DB: users_service
      USERS_MONGO_URL: mongodb://root:passw0rd@mongodb/?ssl=false&authSource=admin
    ports:
      - "3000:3000"
  mongodb:
    image: mongo:5.0.9
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passw0rd
    ports:
      - "27018:27018"
      - "27017:27017"